spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: test1234
announcement:
  hi: "애플리케이션 공통 속성 테스트 중입니다."

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0  # 모든 요청을 추적하도록 샘플링 확률을 100%로 설정합니다. 즉, 시스템을 통과하는 모든 요청이 추적됩니다.
    propagation: # 분산 추적 데이터가 어떻게 넘어가는지를 정의
      consume: b3  # 추적 정보를 수신할 때 사용할 포맷으로 B3(Single) 포맷을 사용합니다. B3은 Zipkin 추적 시스템에서 널리 사용되는 표준입니다. b3 : 추적 ID와 Span ID를 HTTP 헤더로 수신하는 방식
      produce: b3_multi  # 추적 정보를 송신할 때 사용할 포맷으로 B3(Multi-header) 포맷을 사용합니다. 이 포맷은 각 추적 정보(예: 추적 ID, 스팬 ID 등)를 별도의 헤더로 전송합니다. 추적 ID, span ID, 부모 span ID 등을 HTTP 헤더로 전송
    zipkin:
      tracing:
        endpoint: "http://localhost:9411/api/v2/spans"  # Zipkin 서버의 API 엔드포인트를